<?php
/**
 * Message translations.
 * 
 * Ukrainian
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    // А
    
    
    // Б
    
    // В
    'your_name' => 'Як Вас звуть?',
    'your_email' => 'Email',
    'enter_message' => 'Введіте повідомлення',
    'your_review' => 'Ваш відгук',
    'your_request_saved' => 'Ваша заявка збережена',
    'error_occured' => 'Виникла помилка',
    
    // Г
    
    // Д
    
    // Е
    
    
    // Ж
    
    
    // З
    'to_order_seminar' => 'Записатися на семінар',   
    'to_order_study' => 'Записатися на навчання',
    'to_order_equipment_technics_study' => 'Записатися на навчання апаратним методикам',
    'to_order_test_drive' => 'Записатися на тест-драйв',
    'to_order_callback' => 'Замовити зворотний дзвінок',
    'payback_cosmetic_title1' => 'Заповніть форму і ми передзвонимо Вам найближчим часом',
    'payback_business_title1' => 'Заповніть форму і ми передзвонимо Вам найближчим часом, щоб уточнити деталі і розрахувати окупність Вашого бізнесу',
    
    // И
    'to_search' => 'Шукати',
    
    // К
    
    // Л
    
    
    // М
    'mobile_phone' => 'Мобільный телефон',
    'payback_cosmetic_title2' => 'Ми надаємо інформацію виключно професіоналам, тому ми просимо вас надати документи, що підтверджують вашу освіту',
    'we_contact_you_soon' => 'Ми зв`яжемося з Вами найближчим часом',
    
    // Н
    'phone_number' => 'Номер телефону',
    
    // О
    'steel_question-fill_form_and_we_call_you' => 'Залишлись питання? - заповніть форму і ми передзвонимо Вам.',
    'send' => 'Відправити',
    'send_review' => 'Відправити відгук',
    
    
    // П
    'attach_file' => 'Прикріпити файл',
    'visit_our_show_room' => 'Відвідай наш шоу-рум',
    'site_search' => 'Пошук по сайту',
    'error_occured_msg_1' => 'При збереженні заявки виникла помилка сервера',
    'error_occured_msg_2' => 'Спробуйте пізніше або повідомте нам про помилку',
    
    // Р
    'payback_business_title2' => 'Розрахунок ми здійснюємо абсолютно безкоштовно',
    
    // С
    'video_link' => 'Посилання на відео',
    'thank_you!' => 'Дякуємо!',
    
    // Т
    
    
    // У
    
    
    // Ф
    'feedback_form' => 'Форма зворотного зв`язку',
    'subscribe_form' => 'Форма підписки',
    
    // Х
    
    
    // Ц
    
    // Ч
    
    
    // Ш
    
    
    // Щ
    
    
    // Э
    
    
    // Ю
    
    
    // Я
    
];  