<?php

date_default_timezone_set('Europe/Kiev');

if (!isset($ALANG)) $ALANG='ru';

//Словарь
$word['ru']['remind']="Мы напомним";
$word['ua']['remind']="Нагадати";

$word['ru']['tab1']="Общие сведения";
$word['ua']['tab1']="Загальна інформація";

$word['ru']['view_site']="Посмотреть сайт";
$word['ua']['view_site']="Подивитися сайт";

$word['ru']['lang']="Язык";
$word['ua']['lang']="Мова";

$word['ru']['tags']="Тегирование";
$word['ua']['tags']="Теги";

$word['ru']['save']="Сохранить";
$word['ua']['save']="Зберегти";

$word['ru']['login_as']="Вы вошли как";
$word['ua']['login_as']="Ви увійшли як";

$word['ru']['login_ok']="Вы успешно вошли в систему!";
$word['ua']['login_ok']="Ви успішно увійшли в систему!";

$word['ru']['login_error']="Ошибка авторизации, проверьте логин и пароль!";
$word['ua']['login_error']="Помилка авторизації, перевірте логін та пароль!";

$word['ru']['exit_ok']="Вы успешно вышли из системы!";
$word['ua']['exit_ok']="Ви успішно вийшли із системи!";

$word['ru']['last_edit']="Последние действия с записью";
$word['ua']['last_edit']="Остання активність";

$word['ru']['first_edit']="Первая активность";
$word['ua']['first_edit']="Перша активність";

$word['ru']['insert']="Добавить";
$word['ru']['insert_']="добавить";
$word['ru']['home']="Вернуться в начало";
$word['ru']['up']="На уровень выше";
$word['ru']['adminpanel']="Админ панель";
$word['ru']['site']="Сайт";
$word['ru']['user']="Пользователь";
$word['ru']['showsite']="Посмотреть сайт";
$word['ru']['exit']="Выход";
$word['ru']['hello']="Приветсвуем вас";
$word['ru']['auth']="Авторизация";
$word['ru']['login']="Ваш логин";
$word['ru']['pass']="Пароль";
$word['ru']['enter']="Войти";
$word['ru']['set_1']="Установить это поле для материалов этого раздела";
$word['ru']['set_0']="Обнулить это поле для материалов этого раздела";
$word['ru']['so_big_img']="Здесь очень большая картинка! Уменьшайте картинки до 1100 пкс в размере и 400 кб в обьеме!";
$word['ru']['ready']="Сохранить";
$word['ru']['ok']="Выполнено успешно";
$word['ru']['editing']="Редактирование";
$word['ru']['edit']="Редактировать";
$word['ru']['del']="Удалить";
$word['ru']['delthis']="удалить этот материал";
$word['ru']['rubric']="Рубрика";
$word['ru']['rubric2']="рубрику";
$word['ru']['itemeditor']="Редактор материалов";
$word['ru']['ofrub']="рубрики";
$word['ru']['item']="Материал";
$word['ru']['items']="Материалы";
$word['ru']['addnew']="добавить новый";
$word['ru']['add']="добавить";
$word['ru']['makecopy']="Создать копию редактируемого материала";
$word['ru']['loadfile']="Загрузить файл (*.<strong>doc</strong>, <strong>xls</strong>, <strong>pdf</strong>, <strong>swf</strong>, <strong>jpg</strong>, <strong>gif</strong>, <strong>zip</strong>)";
$word['ru']['image']="Картинка";
$word['ru']['image2']="картинку";
$word['ru']['rubricator']="Рубрикатор";
$word['ru']['insertrub']="Вставить рубрику";
$word['ru']['newrub']="Новая рубрика";
$word['ru']['parentrub']="Рубрика выше";
$word['ru']['chldrubs']="Рубрики";
$word['ru']['insertitem']="добавить новый материал в рубрику";
$word['ru']['insertitem_norub']="добавить новую запись";
$word['ru']['treerub']="Рубрики";
$word['ru']['extraparams']="Дополнительные характеристики товаров для этой рубрики";
$word['ru']['extraiparams']="Дополнительные характеристики товара";
$word['ru']['root']="Корень сайта";
$word['ru']['create']="Создать";
$word['ru']['pages']="Страницы";
$word['ru']['constants']="Константы сайта";
$word['ru']['images']="Изображения";
$word['ru']['images_bank']="Загруженные картинки: копируйте отсюда";
$word['ru']['files_bank']="Файлы";
$word['ru']['images_img']="Картинка (JPG или GIF) до 1000 пикселей в ширину:";
$word['ru']['images_preview']="Предпросмотр на сайте";
$word['ru']['width']="Ширина";
$word['ru']['height']="Высота";
$word['ru']['name']="Название";
$word['ru']['insertparam']="Добавить характеристику";
$word['ru']['insertparamg']="Добавить группу характеристик";
$word['ru']['search']="Поиск";
$word['ru']['search_go']="искать";
$word['ru']['lost_p']="Пароль утерян";
$word['ru']['input_day']="Введите сегодняшнее чило";
$word['ru']['rubricator']="Рубрикатор";

$word['eng']['insert']="Insert";
$word['eng']['home']="Home";
$word['eng']['up']="Level up";
$word['eng']['adminpanel']="Admin panel";
$word['eng']['site']="Site";
$word['eng']['user']="User";
$word['eng']['showsite']="Show site";
$word['eng']['exit']="Exit";
$word['eng']['hello']="Hello";
$word['eng']['auth']="Auth";
$word['eng']['login']="Login";
$word['eng']['pass']="Password";
$word['eng']['enter']="Enter";
$word['eng']['set_1']="Set 1 for all";
$word['eng']['set_0']="Set 0 for all";
$word['eng']['so_big_img']="You have very large image! Scale it to 1000 px and 400 kb size!";
$word['eng']['ready']="Submit";
$word['eng']['ok']="ready!";
$word['eng']['editing']="Editing";
$word['eng']['edit']="Edit";
$word['eng']['del']="Del";
$word['eng']['delthis']="del this item";
$word['eng']['rubric']="Rubric";
$word['eng']['rubric2']="rubric";
$word['eng']['itemeditor']="Items editor";
$word['eng']['ofrub']="of rubric";
$word['eng']['item']="Item";
$word['eng']['items']="Items";
$word['eng']['addnew']="add new";
$word['eng']['add']="add new";
$word['eng']['makecopy']="Make copy";
$word['eng']['loadfile']="Upload file (*.<strong>doc</strong>, <strong>xls</strong>, <strong>pdf</strong>, <strong>swf</strong>, <strong>jpg</strong>, <strong>gif</strong>, <strong>zip</strong>)";
$word['eng']['image']="Image";
$word['eng']['image2']="image";
$word['eng']['rubricator']="Rubrics editor";
$word['eng']['insertrub']="Insert rubric";
$word['eng']['newrub']="New rubric";
$word['eng']['parentrub']="Parent rubric";
$word['eng']['chldrubs']="Child rubs";
$word['eng']['insertitem']="add new item in rubric";
$word['eng']['insertitem_norub']="add new item";
$word['eng']['treerub']="Rubrics";
$word['eng']['extraparams']="Extra parameters for this rubric";
$word['eng']['extraiparams']="Extra parameters for this item";
$word['eng']['root']="Sites root";
$word['eng']['create']="Create new item";
$word['eng']['pages']="Pages";
$word['eng']['constants']="Constants";
$word['eng']['images']="Images for site";
$word['eng']['images_bank']="Images: copy from there";
$word['eng']['files_bank']="Uploaded files";
$word['eng']['images_img']="Image file (JPG or GIF, width < 1000px):";
$word['eng']['images_preview']="Small version resize";
$word['eng']['width']="width";
$word['eng']['height']="height";
$word['eng']['name']="title";
$word['eng']['insertparam']="Insert parameter";
$word['eng']['insertparamg']="Insert parameters group";
$word['eng']['search']="Search";
$word['eng']['search_go']="go";
$word['eng']['lost_p']="I have lost password";
$word['eng']['input_day']="Input day of month";
$word['eng']['rubricator']="Rubs";

$word['ua']['insert']="Додати";
$word['ua']['insert_']="додати";
$word['ua']['home'] = "Перейти на початок";
$word['ua']['up'] = "На рівень вище";
$word['ua']['adminpanel'] = "Адмін панель";
$word['ua']['site'] = "Сайт";
$word['ua']['user'] = "Користувач";
$word['ua']['showsite'] = "Переглянути сайт";
$word['ua']['exit'] = "Вихід";
$word['ua']['hello'] = "Вітаємо вас";
$word['ua']['auth'] = "Авторизація";
$word['ua']['login'] = "Логін";
$word['ua']['pass'] = "Пароль";
$word['ua']['enter'] = "Увійти";
$word['ua']['set_1'] = "Встановити це поле для матеріалів цього розділу";
$word['ua']['set_0'] = "обнулити це поле для матеріалів цього розділу";
$word['ua']['so_big_img'] = "Тут дуже велика картинка! Зменшуйте картинки до 1100 ПКС у розмірі та 400 кб в обсязі!";
$word['ua']['ready'] = "Готово";
$word['ua']['ok'] = "Виконано успішно";
$word['ua']['editing'] = "Редагування";
$word['ua']['edit'] = "Редагувати";
$word['ua']['del'] = "Видалити";
$word['ua']['delthis'] = "видалити цей матеріал";
$word['ua']['rubric'] = "Рубрика";
$word['ua']['rubric2'] = "рубрику";
$word['ua']['itemeditor'] = "Редактор матеріалів";
$word['ua']['ofrub'] = "рубрики";
$word['ua']['item'] = "Матеріал";
$word['ua']['items'] = "Матеріали";
$word['ua']['addnew'] = "додати новий";
$word['ua']['add'] = "додати";
$word['ua']['makecopy'] = "Створити копію редагованого матеріалу";
$word['ua']['loadfile'] = "Завантажити файл (*. <strong> doc </ strong>, <strong> xls </ strong>, <strong> pdf </ strong>, <strong> swf </ strong>, <strong> jpg </ strong>, <strong> gif </ strong>, <strong> zip </ strong>) ";
$word['ua']['image'] = "Зображення";
$word['ua']['image2'] = "картинку";
$word['ua']['rubricator'] = "Рубрикатор";
$word['ua']['insertrub'] = "Вставити рубрику";
$word['ua']['newrub'] = "Нова рубрика";
$word['ua']['parentrub'] = "Рубрика вище";
$word['ua']['chldrubs'] = "Рубрики всередині";
$word['ua']['insertitem'] = "додати новий матеріал у рубрику";
$word['ua']['insertitem_norub'] = "додати новий запис";
$word['ua']['treerub'] = "Рубрики";
$word['ua']['extraparams'] = "Параметри матеріалів для цієї рубрики";
$word['ua']['extraiparams'] = "Додаткові параметри матеріалу";
$word['ua']['root'] = "Корінь сайту";
$word['ua']['create'] = "Створити";
$word['ua']['pages'] = "Сторінки";
$word['ua']['constants'] = "Константи сайту";
$word['ua']['images'] = "Картинки для сайту";
$word['ua']['images_bank'] = "Завантажені зображення: копіюйте звідси";
$word['ua']['files_bank'] = "Завантажені файли: копіюйте звідси";
$word['ua']['images_img'] = "Зображення (JPG або GIF) до 1000 пікселів в ширину:";
$word['ua']['images_preview'] = "Передпроглядання на сайті";
$word['ua']['width'] = "Ширина";
$word['ua']['height'] = "Висота";
$word['ua']['name'] = "Назва";
$word['ua']['insertparam'] = "Додати характеристику";
$word['ua']['insertparamg'] = "Додати групу характеристик";
$word['ua']['search'] = "Пошук";
$word['ua']['search_go'] = "шукати";
$word['ua']['lost_p']="Пароль загублено";
$word['ua']['input_day']="Введіть сьогоднішнє число";
$word['ua']['rubricator']="Рубрикатор";

//Автозамена
define('imadd', "<img src=img/add.gif border=0 alt=\"Добавить\" >");
define('implus', "<img src=img/plus.gif border=0 alt=\"Вставить\" >");
define('imed', "<img src=img/edit.gif border=0 alt=\"Редактировать\">");
define('imedm', "<img src=img/edit.gif border=0 alt=\"Изменить\">");
define('imdocs', "<img src=img/docs.gif border=0 alt=\"Материалы\">");
define('imitems', "<img src=img/items.gif border=0 alt=\"Материалы\">");
define('imdel', "<img src=img/del.gif border=0 alt=\"Удалить\">");
define('imdelm', '<i class="glyphicon glyphicon-trash"></i>');
define('im_del_folder', "<img src=img/del_folder.gif border=0 alt=\"Удалить\">");
define('im_del_folder0', "<img src=img/del_folder0.gif border=0 alt=\"Удалить\">");
define('imback', "<img src=img/back.gif border=0 alt=\"Назад\">");
define('imup', "<img src=img/hw_btn_levelup.gif border=0 alt=\"Выше\">");
define('imroot', "<img src=img/hw_btn_home.gif border=0 alt=\"В начало\">");
define('imlook', "<img src=img/look.gif border=0 alt=\"Посмотреть\">");
define('imby', "<a href=http://www.bunke.com.ua target=_blank><img src=img/by.gif border=0 align=right alt=\"Разработано Александром Бунке\"></a>");
define('imfolder', "<img src=img/folder.gif border=0 alt=\"Редактировать раздел\">");
define('imfolder_opened', "<img src=img/folder_opened.gif border=0 alt=\"Войти в раздел\">");
define('imfolder1', "<img src=img/folder1.gif border=0 alt=\"Раздел\">");
define('imfolder_p', "<img src=img/folder_plus.gif border=0 alt=\"Expand\">");
define('im_tree_ugol', "<img src=img/tree_ugol.gif border=0 alt=\"Раздел\">");
define('imfile', "<img src=img/file.gif border=0 alt=\"Добавить/смотреть материал(ы)\">");
define('btn_up', "<img src=img/hw_btn_up.gif border=0 alt=\"UP\">");
define('btn_down', "<img src=img/hw_btn_down.gif border=0 alt=\"DOWN\">");
define('btn_down2', "<img src=img/btn_down2.gif border=0 alt=\"Down max\">");

define('C_FLOAT', 0);
define('C_TEXTLINE', 1);
define('C_TEXT', 2);
define('C_HIDDEN', 3);
define('C_NOGEN', 4);
define('C_SPEC', 5);
define('C_CHECKBOX', 6);
define('C_SIMPLETEXT', 7);
define('C_HR', 8);
define('C_LIST', 9);
define('C_LIST_VALS', 10);
define('C_FILE', 11);

define('C_SHOW', 1);
define('C_NOTSHOW', 0);

define('C_EDIT', 1);
define('C_NOTEDIT', 0);
?>
