<?php
/**
 * Message translations.
 * 
 * English
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    // А
    'no_analogs' => 'No analogs in Ukraine!',
    'address' => 'Address',
    
    // Б
    'charity' => 'Charity',
    'blog' => 'Blog',
    'employee_bonus' => 'Employee bonus',
    'business-a' => 'Business',
    'consulting' => 'Business consulting',
    
    // В
    'choose_category' => 'Choose category',
    'all_categories' => 'All categories',
    'choose_apparat' => 'Choose product',
    'per_day' => 'Per day',
    'per_month' => 'Per month',
    'per_year' => 'Per year',
    'you_may_interested' => 'You may interested',
    'kit_consist' => 'Kit consists',
    'stocks' => 'Stocks',
    'down' => 'Down',
    'all_brands' => 'All brands',
    'all_technologies' => 'All technologies',
    
    // Г
    'main' => 'Home',
    'year' => 'year',
    
    // Д
    'other_posts' => 'Other posts',
    'other_events' => 'Other events',
    'happy_clients' => 'Satisfied clients',
    'home_line' => 'Home line',
    'projects_title' => 'Professional beauty and health industry',
    'for_professionals' => 'For professionals',
    
    // Е
    
    
    // Ж
    
    
    // З
    'test-drive' => 'to order equipment test-drive',
    'to_order_study' => 'to order study',
    'to_order_test-drive' => 'to schedule a free test-drive',
    'to_seminar' => 'to schedule seminar, study',
    'signup' => 'Signup',
    
    
    // И
    'industy_beauty_and_health' => 'of beauty and health industry',
    
    // К
    'team' => 'Team',
    'cosmetic-i' => 'cosmetic',
    'cosmetic' => 'cosmetics',
    'work_days_number' => 'number of work days',
    'procedures_per_day_number' =>  'number of procedures per day',
    'sanatorii' => 'Clinics and sanatoria',
    'who_trust?' => 'Who trusts us?',
    'contacts' => 'Contacts',
    
    // Л
    
    
    // М
    'mobile-cosmo' => 'Mobile cosmetologies',
    'medicine' => 'medicine',
    'furniture' => 'furniture',
    'we_use_only_quality' => 'We use only quality',
    'world_technologies' => 'world technologies',
    
    // Н
    'our_trainers' => 'Our trainers',
    'our_fields' => 'Our areas',
    'our_clients' => 'Our clients',
    
    // О
    'equipment-ya' => 'Equipment',
    'equipment' => 'Equipment',
    'hotels' => 'hotels',
    'reviews' => 'Reviews',
    'study' => 'Study',
    'equipment_and_furniture' => 'Equipment & furniture',
    'equipment_technics_study' => 'Equipment technics study',
    'about' => 'About',
    'cosmetologs_study' => 'Cosmetologs study',
    'open_for_you' => 'will open for you',
    
    // П
    'partners' => 'Partners',
    'show-room' => 'Visit our show room',
    'subscribe_blog' => 'Subscribe out blog',
    'read_more' => 'More',
    'profit' => 'Profit',
    'profit_trend' => 'Profit trend',
    'pro_cosmetic' => 'Professional cosmetic',
    'pro_line' => 'Professional line',
    'by_technologies' => 'Technologies',
    'by_brands' => 'Brands',
    'subscribe_channel' => 'Subscribe out channel',
    'projects' => 'Projects',
    'site_search' => 'Site search',
    'show_more' => 'Show more',
    'privacy_politic' => 'Privacy policy',
    'no_search_results' => 'Nothing found under request',
    
    // Р
    'calculate_effect' => 'Calculate payback',
    'calculate_equipment_effect' =>  'Calculate equipment payback',
    'procedure_cost' => 'Procedure cost',
    'consumables' => 'Consumables',
    'calculate' => 'Calculate',
    'done_projects' => 'Implemented projects',
    'calculate_procedure_profit' => 'Calculate profitability of procedures',
    'shedule' => 'Seminars schedule',
    
    
    // С
    'procedure_price' => 'Procedure price',
    'salony' => 'Beauty salons',
    'spa-wellness' => 'SPA centers',
    'employees_stuff' => 'Employees in the stuff',
    'spa-wellness' => 'SPA & Fitness',
    'events' => 'Events',
    'seminar' => 'Seminar',
    'seminar_lead' => 'Seminar lead',
    'new_capabilities' => 'completely new possibilities',
    'service-center' => 'Service center',
    
    // Т
    'topic' => 'Topic',
    'trainers' => 'Trainers',
    
    // У
    'services' => 'Services',
    'study_center' => 'Study center',
    
    // Ф
    'fintes' => 'Fitness centers',
    
    // Х
    
    
    // Ц
    'values' => 'Values',
    
    // Ч
    'for_private_persons' => 'Private persons',
    
    // Ш
    
    
    // Щ
    
    
    // Э
    'estetic_and_cosmetology' => 'Esthetics and cosmetology',
    
    // Ю
    
    
    // Я
    
];
?>
