<?php
/**
 * Message translations.
 * 
 * English
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    // А
    
    
    // Б
    
    // В
    'your_name' => 'Name',
    'your_email' => 'Email',
    'enter_message' => 'Enter message',
    'your_review' => 'Your review',
    'your_request_saved' => 'Your request is saved',
    'error_occured' => 'An error occurred',
    
    // Г
    
    // Д
    
    // Е
    
    
    // Ж
    
    
    // З
    'to_order_seminar' => 'Apply for a seminar',   
    'to_order_study' => 'Apply for a study',
    'to_order_equipment_technics_study' => 'Apply for hardware training methods',
    'to_order_test_drive' => 'Apply for test drive',
    'to_order_callback' => 'Request callback',
    'payback_cosmetic_title1' => 'Fill the form and we will call you as soon as',
    'payback_business_title1' => 'Fill the form and we will call you back in the near future to clarify details and to calculate payback on your business',
    
    // И
    'to_search' => 'Search',
    
    // К
    
    // Л
    
    
    // М
    'mobile_phone' => 'Mobile phone',
    'payback_cosmetic_title2' => 'We provide information exclusively for professionals, so we ask you to provide proof of your education',
    'we_contact_you_soon' => 'We will contact you shortly',
    
    // Н
    'phone_number' => 'Phone number',
    
    // О
    'steel_question-fill_form_and_we_call_you' => 'Still have questions? - Fill in the form and we will call you back.',
    'send' => 'Send',
    'send_review' => 'Send review',
    
    
    // П
    'attach_file' => 'Attach a file',
    'visit_our_show_room' => 'Visit our show room',
    'site_search' => 'Search',
    'error_occured_msg_1' => 'Server error occurred when request saved',
    'error_occured_msg_2' => 'Try again later or let us know about a problem',
    
    // Р
    'payback_business_title2' => 'The calculation we perform for free',
    
    // С
    'video_link' => 'Video link',
    'thank_you!' => 'Thank you!',
    
    // Т
    
    
    // У
    
    
    // Ф
    'feedback_form' => 'Feedback form',
    'subscribe_form' => 'Subscribe form',
    
    // Х
    
    
    // Ц
    
    // Ч
    
    
    // Ш
    
    
    // Щ
    
    
    // Э
    
    
    // Ю
    
    
    // Я
    
];  