<?php
/**
 * Message translations.
 * 
 * RUSSIAN
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    // А
    'no_analogs' => 'Аналогов в Украине нет!',
    'address' => 'Адрес',
    
    // Б
    'charity' => 'Благотворительность',
    'blog' => 'Блог',
    'employee_bonus' => 'Бонус сотрудников',
    'business-a' => 'Бизнеса',
    'consulting' => 'Бизнес консалтинг',
    
    // В
    'choose_category' => 'Выберите категорию',
    'all_categories' => 'Все категории',
    'choose_apparat' => 'Выберите аппарат',
    'per_day' => 'В день',
    'per_month' => 'В месяц',
    'per_year' => 'В год',
    'you_may_interested' => 'Вас также сможет заинтересовать',
    'kit_consist' => 'В набор включены',
    'stocks' => 'Выгодные предложения',
    'down' => 'Вниз',
    'all_brands' => 'Все бренды оборудования',
    'all_technologies' => 'Все технологии оборудования',
    
    
    
    // Г
    'main' => 'Главная',
    'year' => 'год',
    
    // Д
    'other_posts' => 'Другие статьи',
    'other_events' => 'Другие события',
    'happy_clients' => 'Довольных клиентов',
    'home_line' => 'Домашняя линия',
    'projects_title' => 'Для профессионалов индустрии красоты и здоровья',
    'for_professionals' => 'ДЛЯ ПРОФЕССИОНАЛОВ',
    
    
    // Е
    
    
    // Ж
    
    
    // З
    'test-drive' => 'заказать тест-драйв оборудования',
    'to_order_study' => 'Закажи обучение',
    'to_order_test-drive' => 'Запишись на бесплатный тест-драйв',
    'to_seminar' => 'Запишись на семинар, обучение',
    'signup' => 'Зарегистрироваться',
    
    
    // И
    'industy_beauty_and_health' => 'индустрии красоты и здоровья',
    
    
    // К
    'team' => 'Команда',
    'cosmetic-i' => 'Косметики',
    'cosmetic' => 'Косметика',
    'work_days_number' => 'Количество рабочих дней',
    'procedures_per_day_number' =>  'Количество процедур в день',
    'sanatorii' => 'клиники и санатории',
    'who_trust?' => 'Кто нам доверяет?',
    'contacts' => 'Контакты',
    
    // Л
    
    
    // М
    'mobile-cosmo' => 'мобильные косметологи',
    'medicine' => 'медицина',
    'furniture' => 'мебель',
    'we_use_only_quality' => 'Мы используем исключительно качественные',
    'world_technologies' => 'мировые технологии',
    
    // Н
    'our_trainers' => 'наши тренеры',
    'our_fields' => 'Наша специализация',
    'our_clients' => 'Наши клиенты',
    
    // О
    'equipment-ya' => 'Оборудования',
    'equipment' => 'Оборудование',
    'hotels' => 'отели',
    'reviews' => 'Отзывы',
    'study' => 'Обучение',
    'equipment_and_furniture' => 'Оборудование и мебель',
    'equipment_technics_study' => 'обучение аппаратным методикам',
    'about' => 'О нас',
    'cosmetologs_study' => 'Обучение косметологов',
    'open_for_you' => 'открываем перед вами',
    
    // П
    'partners' => 'Партнеры',
    'show-room' => 'Посети наш шоу-рум',
    'subscribe_blog' => 'Подпишись на наш блог',
    'read_more' => 'Подробнее',
    'profit' => 'Прибыль',
    'profit_trend' => 'Прибыль в динамике',
    'pro_cosmetic' => 'Профессиональная косметика',
    'pro_line' => 'Профессиональная линия',
    'by_technologies' => 'По технологиям',
    'by_brands' => 'По брендам',
    'subscribe_channel' => 'Подпишись на наш канал',
    'projects' => 'Проекты',
    'site_search' => 'Поиск по сайту',
    'show_more' => 'Показать еще',
    'privacy_politic' => 'Политика конфиденциальности',
    'no_search_results' => 'По данному запросу ничего не найдено',
    
    // Р
    'calculate_effect' => 'Рассчитать окупаемость',
    'calculate_equipment_effect' =>  'Рассчитать окупаемость оборудования',
    'procedure_cost' => 'Расходы на процедуру',
    'consumables' => 'Расходные материалы',
    'calculate' => 'Рассчитать',
    'done_projects' => 'Реализованных проектов',
    'calculate_procedure_profit' => 'Рассчитать доходность процедуры',
    'shedule' => 'Расписание семинаров',
    
    
    // С
    'procedure_price' => 'Стоимость процедуры',
    'salony' => 'салоны красоты',
    'spa-wellness' => 'SPA центры',
    'employees_stuff' => 'Сотрудников в штате',
    'spa-wellness' => 'SPA и фитнес',
    'events' => 'События',
    'seminar' => 'Семинар',
    'seminar_lead' => 'Семинар проводит',
    'new_capabilities' => 'совершенно новые возможности',
    'service-center' => 'Сервисный центр',
    
    // Т
    'topic' => 'Тема',
    'trainers' => 'Тренеры',
    
    // У
    'services' => 'Услуги',
    'study_center' => 'Учебный центр',
    
    // Ф
    'fintes' => 'фитнес центры',
    
    // Х
    
    
    // Ц
    'values' => 'Ценности',
    
    // Ч
    'for_private_persons' => 'Частным лицам',
    
    // Ш
    
    
    // Щ
    
    
    // Э
    'estetic_and_cosmetology' => 'эстетика и косметология',
    
    // Ю
    
    
    // Я
    
];
?>
