<?php
/**
 * Message translations.
 * 
 * RUSSIAN
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    // А
    
    
    // Б
    
    // В
    'your_name' => 'Как Вас зовут?',
    'your_email' => 'Email',
    'enter_message' => 'Введите сообщение',
    'your_review' => 'Ваш отзыв',
    'your_request_saved' => 'Ваша заявка сохранена',
    'error_occured' => 'Возникла ошибка',
    
    
    // Г
    
    // Д
    
    // Е
    
    
    // Ж
    
    
    // З
    'to_order_seminar' => 'Записаться на семинар',    
    'to_order_study' => 'Записаться на обучение',    
    'to_order_equipment_technics_study' => 'Записаться на обучение аппаратным методикам',
    'to_order_test_drive' => 'Записаться на тест-драйв',
    'to_order_callback' => 'Заказать обратный звонок',
    'payback_cosmetic_title1' => 'Заполните форму и мы перезвоним Вам в ближайшее время',
    'payback_business_title1' => 'Заполните форму и мы перезвоним Вам в ближайшее время, чтобы уточнить детали и рассчитать окупаемость Вашего бизнеса',
    
    // И
    'to_search' => 'Искать',
    
    // К
    
    // Л
    
    
    // М
    'mobile_phone' => 'Мобильный телефон',
    'payback_cosmetic_title2' => 'Мы предоставляем информацию исключительно профессионалам, поэтому мы просим вас предоставить документы, подтверждающие ваше образование',
    'we_contact_you_soon' => 'Мы свяжемся с Вами в ближайшее время',
    
    // Н
    'phone_number' => 'Номер телефона',
    
    // О
    'steel_question-fill_form_and_we_call_you' => 'Остались вопросы? - заполните форму и мы перезвоним Вам.',
    'send' => 'Отправить',
    'send_review' => 'Отправить отзыв',
    
    
    // П
    'attach_file' => 'Прикрепить файл',
    'visit_our_show_room' => 'Посети наш шоу-рум',
    'site_search' => 'Поиск по сайту',
    'error_occured_msg_1' => 'При сохранении заявки возникла ошибка сервера',
    'error_occured_msg_2' => 'Попробуйте позже или сообщите нам о проблеме',
    
    // Р
    'payback_business_title2' => 'Рассчет мы осуществляем абсолютно бесплатно',
    
    // С
    'video_link' => 'Ссылка на видео',
    'thank_you!' => 'Спасибо!',
    
    // Т
    
    
    // У
    
    
    // Ф
    'feedback_form' => 'Форма обратной связи',
    'subscribe_form' => 'Форма подписки',
    
    
    // Х
    
    
    // Ц
    
    // Ч
    
    
    // Ш
    
    
    // Щ
    
    
    // Э
    
    
    // Ю
    
    
    // Я
    
];  