<?php
/**
 * Message translations.
 * 
 * Ukrainian
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    // А
    'no_analogs' => 'Аналогів в Україні немає!',
    'address' => 'Адреса',
    
    // Б
    'charity' => 'Благодійність',
    'blog' => 'Блог',
    'employee_bonus' => 'Бонус співробітників',
    'business-a' => 'Бизнесу',
    'consulting' => 'Бизнес консалтинг',
    
    // В
    'choose_category' => 'Оберіть категорію',
    'all_categories' => 'Всі категорії',
    'choose_apparat' => 'Оберіть апарат',
    'per_day' => 'В день',
    'per_month' => 'В місяць',
    'per_year' => 'В рік',
    'you_may_interested' => 'Вас також може зацікавити',
    'kit_consist' => 'В набір включені',
    'stocks' => 'Вигідні пропозиції',
    'down' => 'Вниз',
    'all_brands' => 'Усі бренди обладнання',
    'all_technologies' => 'Усі технології обладнання',
    
    // Г
    'main' => 'Головна',
    'year' => 'рік',
    
    // Д
    'other_posts' => 'Інші статті',
    'other_events' => 'Інші події',
    'happy_clients' => 'Задоволених клієнтів',
    'home_line' => 'Домашня лінія',
    'projects_title' => 'Для професіоналів індустрії краси і здоров`я',
    'for_professionals' => 'Для професіоналів',
    
    // Е
    
    
    // Ж
    
    
    // З
    'test-drive' => 'замовити тест-драйв обладнання',
    'to_order_study' => 'Замовити навчання',
    'to_order_test-drive' => 'Запишися на безкоштовний тест-драйв',
    'to_seminar' => 'Запишися на семінар, навчання',
    'signup' => 'Зареєструватися',
    
    
    // И
    'industy_beauty_and_health' => 'індустрії краси і здоров`я',
    
    // К
    'team' => 'Команда',
    'cosmetic-i' => 'Косметики',
    'cosmetic' => 'Косметика',
    'work_days_number' => 'Кількість робочих днів',
    'procedures_per_day_number' =>  'Кількість процедур за день',
    'sanatorii' => 'клініки і санаторії',
    'who_trust?' => 'Хто нам довіряє?',
    'contacts' => 'Контакти',
    
    // Л
    
    
    // М
    'mobile-cosmo' => 'мобильні косметологи',
    'medicine' => 'медицина',
    'furniture' => 'меблі',
    'we_use_only_quality' => 'Ми використовуємо виключно якісні',
    'world_technologies' => 'світові технології',
    
    // Н
    'our_trainers' => 'наші тренери',
    'our_fields' => 'Наша спеціалізація',
    'our_clients' => 'Наші кліенти',
    
    // О
    'equipment-ya' => 'Обладнання',
    'equipment' => 'Обладнання',
    'hotels' => 'готелі',
    'reviews' => 'Відгуки',
    'study' => 'Навчання',
    'equipment_and_furniture' => 'Обладнання і меблі',
    'equipment_technics_study' => 'навчання апаратним методикам',
    'about' => 'Про нас',
    'cosmetologs_study' => 'Навчання косметологів',
    'open_for_you' => 'відкриє перед вами',
    
    // П
    'partners' => 'Партнери',
    'show-room' => 'Відвідай наш шоу-рум',
    'subscribe_blog' => 'Підпишись на наш блог',
    'read_more' => 'Детальніше',
    'profit' => 'Прибуток',
    'profit_trend' => 'Прибуток в динаміці',
    'pro_cosmetic' => 'Професійна косметика',
    'pro_line' => 'Професійна линія',
    'by_technologies' => 'По технологіям',
    'by_brands' => 'По брендам',
    'subscribe_channel' => 'Підпишись на наш канал',
    'projects' => 'Проекти',
    'site_search' => 'Пошук по сайту',
    'show_more' => 'Показати ще',
    'privacy_politic' => 'Політика конфіденційності',
    'no_search_results' => 'За даним запитом нічого не знайдено',
    
    // Р
    'calculate_effect' => 'Розрахувати окупність',
    'calculate_equipment_effect' =>  'Розрахувати окупність обладнання',
    'procedure_cost' => 'Витрати на процедуру',
    'consumables' => 'Витратні матеріали',
    'calculate' => 'Розрахувати',
    'done_projects' => 'Реалізованих проектів',
    'calculate_procedure_profit' => 'Розрахувати дохідність процедури',
    'shedule' => 'Розклад семінарів',
    
    
    // С
    'procedure_price' => 'Вартість процедури',
    'salony' => 'салони краси',
    'spa-wellness' => 'SPA центри',
    'employees_stuff' => 'Співробітників у штаті',
    'spa-wellness' => 'SPA і фітнес',
    'events' => 'Події',
    'seminar' => 'Семінар',
    'seminar_lead' => 'Семінар проводить',
    'new_capabilities' => 'зовсім нові можливості',
    'service-center' => 'Сервісний центр',
    
    // Т
    'topic' => 'Тема',
    'trainers' => 'Тренери',
    
    // У
    'services' => 'Послуги',
    'study_center' => 'Навчальний центр',
    
    // Ф
    'fintes' => 'фітнес центри',
    
    // Х
    
    
    // Ц
    'values' => 'Цінності',
    
    // Ч
    'for_private_persons' => 'Приватним особам',
    
    // Ш
    
    
    // Щ
    
    
    // Э
    'estetic_and_cosmetology' => 'естетика і косметологія',
    
    // Ю
    
    
    // Я
    
];
?>
